### ISSUE TITLE
What does this 'elem' means?

### ISSUE THREAD

**Issue by C-SunRay** [wookayin/pintos#4]
wonder what ‘elem’ represents in this‘
I find no declare of this.
![image](https://user-images.githubusercontent.com/57622222/147383423-6b3e5eaf-7d0c-4f40-afb0-9d22a2925304.png)

**Comment by fengxiaohu** [comment]
may be it is a linked list of strcut pointer(thread)

**Comment by Wangch29** [comment]
It means one attribute in struct thread definition, like:

struct thread
{
    tid_t tid;
    char name[16];
    struct list_elem elem;
    unsigned magic; 
}

elem means the attribute named "elem" in your struct thread.
